doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      sms_id: Sms\Infrastructure\Persistence\Doctrine\Types\SmsIdType
      messagetext: Sms\Infrastructure\Persistence\Doctrine\Types\MessageTextType
      phonenumber: Sms\Infrastructure\Persistence\Doctrine\Types\PhoneNumberType
      
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      Sms:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: 'Sms\Domain\Model\SmsModel'
        alias: Sms