services:
  nginx-devlocal:
    container_name: "sms-nginx"
    image: sms-nginx:latest
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - sms-php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/sms"
    ports:
      - "172.17.0.1:11380:80"
    networks:
      - sms-network

  sms-php:
    container_name: "sms-php"
    image: sms-php:latest
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/sms"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    depends_on:
      sms-mariadb:
        condition: service_started
    networks:
      - sms-network

  sms-mariadb:
    image: sms-mariadb:latest
    container_name: "sms-mariadb"
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    restart: always
    volumes:
      - /home/debian/projet/sms-mariadb/_data:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./mariadb/db.env
    networks:
      - sms-network
  
  sms-phpmyadmin:
    image: phpmyadmin
    container_name: "sms-phpmyadmin"
    restart: always
    environment:
      PMA_HOST: sms-mariadb
    depends_on:
      - sms-mariadb
    ports:
      - "172.17.0.1:11390:80"
    networks:
      - sms-network

  sms-swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "sms-swagger-ui"
    restart: always
    environment:
      PORT_IPV6: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      SWAGGER_JSON: /v1/doc.yaml
    volumes:
      - ./swagger/v1:/v1
    ports:
      - "172.17.0.1:11302:8080"
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge
    name: sms-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:2c::/112
          gateway: fdff:1:2c::1

volumes:
  sms-db: