openapi: 3.1.0
info:
  title: Sms API
  version: 1.0.0
servers:
  - url: /api/v1
    description: API routes
  - url: http://172.17.0.1:11380/api/v1
    description: Local server
paths:
  /sms/send:
    post:
      summary: Sending an SMS
      operationId: Sms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messageText:
                  type: string
                  description: The text of the sent SMS
                  example: Hello, this is a test message.
                phoneNumber:
                  type: string
                  description: The phone number to which the SMS was sent
                  example: "+33601020304"
      responses:
        '200':
          description: SMS successfully sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the SMS send was successful
                    example: true
                  statusCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example:
                  data:
                    type: object
                    description: Details about the sent SMS
                    properties:
                      statusMessage:
                        type: string
                        description: A status message
                        example: Message sent successfully
                      smsId:
                        type: string
                        description: Sms identity
                        example: sms_123456780
        '402':
          description: Payment required
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the SMS send was successful
                    example: false
                  statusCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: SmsApiBadResponseException
                  data:
                    type: object
                    example:
